In [7]:
import numpy as np
import scipy as sp

In [3]:
 m = np.array([[1, 5, 2],[4, 7, 4],[2, 0, 9]])
 m

array([[1, 5, 2],
       [4, 7, 4],
       [2, 0, 9]])

In [4]:
m.transpose()

array([[1, 4, 2],
       [5, 7, 0],
       [2, 4, 9]])

In [5]:
np.linalg.inv(m)

array([[-0.6       ,  0.42857143, -0.05714286],
       [ 0.26666667, -0.04761905, -0.03809524],
       [ 0.13333333, -0.0952381 ,  0.12380952]])

In [6]:
np.linalg.det(m)

-105.00000000000006

In [18]:
nums = np.random.randint(1,100, size=(1,200)) 
nums

array([[ 7, 10, 15, 47, 45, 63, 49, 95, 34, 66, 60, 95, 66, 99, 40, 30,
        35, 39, 44, 67, 91, 74,  1, 43, 65, 10, 47, 35, 97, 92,  8, 96,
        92, 87, 58, 65,  3, 12, 32, 70, 47, 13, 67, 84, 53, 76, 91, 47,
        67, 12, 66, 97, 64, 51, 81,  1, 10,  2, 58, 65, 40, 17, 89, 26,
        50, 59, 85, 73, 59, 10, 53, 58, 55, 94, 38,  6, 17, 52, 72, 76,
        21, 69, 77, 93, 54, 12, 22, 31, 18, 39, 38, 75, 22, 81,  3, 50,
        62, 77, 43, 66, 73,  8, 46, 59, 43, 33, 55, 25,  2, 38, 58, 56,
        31, 26, 21, 35, 17, 71,  5, 49, 96, 44, 17, 22, 37, 90, 82, 80,
        76, 57, 51, 87, 30, 12, 98, 48, 34, 54, 46, 56, 57, 66, 93, 86,
        93, 90, 34, 53, 90, 70, 59, 75, 87, 58,  4, 42, 81, 25,  9, 10,
        41, 36, 78, 97, 54, 35, 78, 69, 47, 11, 43, 61, 40, 47, 67, 77,
        44, 27, 46, 79, 94, 11, 97, 50, 25,  9, 89, 53, 82, 37, 14, 64,
        84, 62, 55, 42, 17, 62, 94, 36]])

In [34]:
# get descriptive stats
print ('Mean:', np.mean(nums)),
print ('Median:', np.median(nums))
# print ('Mode:', np.mode(nums))
print ('Standard Deviation:', np.std(nums))
print ('Variance:', np.var(nums))
# print ('Skew:', np.stats.skew(nums))
# print ('Kurtosis:', np.kurtosis(nums))

Mean: 51.61
Median: 53.0
Standard Deviation: 27.293367326147205
Variance: 744.9278999999999
