In [18]:
import matplotlib.pyplot as plt, numpy as np, pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA

In [5]:
data = pd.read_csv('../dataset/Varr_supp.csv', index_col = 0)

In [6]:
data

PRIX  R_POIDS_PUIS FINITION
Modele                                       
Alfasud TI       30570        11.013      2_B
Audi 100         39990        13.059     3_TB
Simca 1300       29600        15.441      1_M
Citroen GS Club  28250        15.763      1_M
Fiat 132         34900        11.276      2_B
Lancia Beta      35480        13.171     3_TB
Peugeot 504      32300        14.684      2_B
Renault 16 TL    32000        18.364      2_B
Renault 30       47700        10.313     3_TB
Toyota Corolla   26540        14.818      1_M
Alfetta-1.66     42395         9.725     3_TB
Princess-1800    33990        14.146      2_B
Datsun-200L      43980        11.913     3_TB
Taunus-2000      35010        11.020      2_B
Rancho           39450        14.113     3_TB
Mazda-9295       27900        13.193      1_M
Opel-Rekord      32700        11.200      2_B
Lada-1300        22100        14.044      1_M

In [10]:
data = pd.get_dummies(data)

In [11]:
data

PRIX  R_POIDS_PUIS  FINITION_1_M  FINITION_2_B  \
Modele                                                             
Alfasud TI       30570        11.013             0             1   
Audi 100         39990        13.059             0             0   
Simca 1300       29600        15.441             1             0   
Citroen GS Club  28250        15.763             1             0   
Fiat 132         34900        11.276             0             1   
Lancia Beta      35480        13.171             0             0   
Peugeot 504      32300        14.684             0             1   
Renault 16 TL    32000        18.364             0             1   
Renault 30       47700        10.313             0             0   
Toyota Corolla   26540        14.818             1             0   
Alfetta-1.66     42395         9.725             0             0   
Princess-1800    33990        14.146             0             1   
Datsun-200L      43980        11.913             0             0   
Taunus-2000      35010        11.020             0             1   
Rancho           39450        14.113             0             0   
Mazda-9295       27900        13.193             1             0   
Opel-Rekord      32700        11.200             0             1   
Lada-1300        22100        14.044             1             0   

                 FINITION_3_TB  
Modele                          
Alfasud TI                   0  
Audi 100                     1  
Simca 1300                   0  
Citroen GS Club              0  
Fiat 132                     0  
Lancia Beta                  1  
Peugeot 504                  0  
Renault 16 TL                0  
Renault 30                   1  
Toyota Corolla               0  
Alfetta-1.66                 1  
Princess-1800                0  
Datsun-200L                  1  
Taunus-2000                  0  
Rancho                       1  
Mazda-9295                   0  
Opel-Rekord                  0  
Lada-1300                    0

In [12]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 18 entries, Alfasud TI to Lada-1300
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   PRIX           18 non-null     int64  
 1   R_POIDS_PUIS   18 non-null     float64
 2   FINITION_1_M   18 non-null     uint8  
 3   FINITION_2_B   18 non-null     uint8  
 4   FINITION_3_TB  18 non-null     uint8  
dtypes: float64(1), int64(1), uint8(3)
memory usage: 486.0+ bytes


In [13]:
scaler = StandardScaler()
scaler.fit(data)

StandardScaler()

In [17]:
scaled_data = scaler.transform(data)
print(scaled_data)

[[-0.5619123  -0.99857454 -0.62017367  1.25356634 -0.70710678]
 [ 0.91309117 -0.05614455 -0.62017367 -0.79772404  1.41421356]
 [-0.71379694  1.041054    1.61245155 -0.79772404 -0.70710678]
 [-0.92518279  1.18937388  1.61245155 -0.79772404 -0.70710678]
 [ 0.11608824 -0.87743129 -0.62017367  1.25356634 -0.70710678]
 [ 0.20690586 -0.00455503 -0.62017367 -0.79772404  1.41421356]
 [-0.29102525  0.69236412 -0.62017367  1.25356634 -0.70710678]
 [-0.33799988  2.38744837 -0.62017367  1.25356634 -0.70710678]
 [ 2.12033923 -1.32100904 -0.62017367 -0.79772404  1.41421356]
 [-1.1929382   0.7540873   1.61245155 -0.79772404 -0.70710678]
 [ 1.28967114 -1.59185402 -0.62017367 -0.79772404  1.41421356]
 [-0.02640148  0.44455017 -0.62017367  1.25356634 -0.70710678]
 [ 1.53785379 -0.58401589 -0.62017367 -0.79772404  1.41421356]
 [ 0.13331227 -0.99535019 -0.62017367  1.25356634 -0.70710678]
 [ 0.82853683  0.42934969 -0.62017367 -0.79772404  1.41421356]
 [-0.97998653  0.00557863  1.61245155 -0.79772404 -0.70

In [38]:
pca= PCA()

In [39]:
x_pca = pca.fit_transform(scaled_data)

In [40]:
x_pca

array([[-9.74722126e-02,  1.68377891e+00, -8.78020541e-01,
         3.91673547e-01,  1.45760560e-16],
       [ 1.64149689e+00, -8.78664291e-01,  5.88125690e-01,
         2.13100727e-01, -1.17741872e-16],
       [-1.89466031e+00, -1.24036522e+00,  6.94638477e-02,
        -4.43389645e-01,  2.88157813e-16],
       [-2.07887849e+00, -1.25462106e+00,  1.64405230e-01,
        -2.89996920e-01,  9.23390764e-17],
       [ 2.47829914e-01,  1.65381282e+00, -6.46778607e-01,
        -1.56738753e-01, -1.82456137e-17],
       [ 1.20870331e+00, -8.69995904e-01,  5.06839476e-01,
         7.67506990e-01,  2.10033343e-16],
       [-6.35278657e-01,  1.46351102e+00,  6.88741599e-01,
         1.72993782e-02,  7.22087910e-17],
       [-1.36004224e+00,  1.24956387e+00,  2.20179348e+00,
        -1.05727385e-01, -3.33447066e-17],
       [ 2.86547462e+00, -7.44265936e-01, -3.29114096e-01,
        -6.23449831e-01, -1.44232518e-17],
       [-2.05584354e+00, -1.19365379e+00, -2.74694322e-01,
        -3.67947666e-02

In [41]:
pca.explained_variance_ratio_

array([5.35073362e-01, 3.13467594e-01, 1.29316080e-01, 2.21429644e-02,
       2.43711135e-33])

In [46]:
np.sum(pca.explained_variance_ratio_)

0.9778570355648085

In [43]:
pca.explained_variance_

array([2.83274133e+00, 1.65953432e+00, 6.84614540e-01, 1.17227459e-01,
       1.29023542e-32])